<?php
$lang = isset($_SESSION['SES_LANG']) ?  $_SESSION['SES_LANG'] : 'id';;

if ($lang == "en") {
    define("_WELCOME", "Welcome");
    define("_HOME", "Home");
    define("_SEARCH", "Search");
    define("_DASHBOARD", "Dashboard");
    define("_FAVOURITE", "Favourite");
    define("_PROFILE", "Profile");
    define("_USERPROFILE", "User Profile");
    define("_USERGUIDE", "User Guide");
    define("_HELP", "Help");
    define("_LANGUAGE", "Language");
    define("_LOGOUT", "Logout");
    define("_5LATESTSOP", "5 Latest SOP");
    define("_5LATESTIM", "5 Latest Internal Memo");
    define("_TITLE", "Title");
    define("_DATE", "Date");
    define("_DOCUMENT", "Content");
    define("_PAGE", "Page");
    define("_SEARCHRESULT", "Search Results of");
    define("_SELECT", "Select");
    define("_CATEGORY", "Category");
    define("_ALL", "All");
    define("_ACTIVITYREPORT", "User Activity Report");
    define("_5LASTREAD", "5 Last Access Digital Content");
    define("_5MOSTREAD", "5 Most Access Digital Content");
    define("_CODE", "Code");
    define("_ADDTOFAVOURITE", "Add to favourite");
    define("_DELETEFROMFAVOURITE", "Delete from favourite");
    define("_VIEWDOCUMENT", "View document detail");
    define("_DATE_SOP", "SK Date");
    define("_DATE_IM", "Memo Date");
    define("_DATE_READING", "Reading Date");
    define("_BACK", "Back");
    define("_POPULARBOOK", "Popular Digital Content");
    define("_NEWBOOK", "Recent Digital Content");
    define("_AUTHOR", "Owner");
    define("_PUBLISHER", "Merk");
    define("_LOCATION", "Location");
    define("_READ", "Read");
    define("_FILENAME", "File Name");
    define("_SIZE", "Size");
    define("_YEAR", "Year");
    define("_DESC", "Description");
    define("_BOOKDETAIL", "Content Detail");
    define("_RATING", "Rating");
    define("_BOOK", "Content");
    define("_SHOW", "Showing");
    define("_ORDER", "Order By");
    define("_NEW", "Newest");
    define("_OLD", "Oldest");
    define("_HIGHEST", "Highest Rating");
    define("_TYPE", "Type");
    define("_PHYSICAL", "Education Asset");
    define("_DIGITAL", "Digital Content");
    define("_ABOVE", "Above");
    define("_BORROW", "Borrowed");
    define("_BY", "By");
    define("_PREVIOUS", "Previous");
    define("_NEXT", "Next");
    define("_INFORMATION", "Information, News, Article");
    define("_MORE", "View More");
    define("_REC", "Recommendation Content");
    define("_AVAILABLE", "Availability");
    define("_ALREADYREAD", "Already Access this contet?");
    define("_SHARE", "Share your opinion with other reader");
    define("_DESCRIPTION", "Description");
    define("_SEND", "Send");
    define("_BOOKMARKADD", " Add to Bookmark");
    define("_BOOKMARKDELETE", " Delete From Bookmark");
    define("_THOUGHT", "Share your opinion");
    define("_NEWS", "News");
    define("_INFORMATION2", "Information");
    define("_ARTICLE", "Article");
    define("_DETAIL", "Details");
    define("_RACK", "Location");

}

if ($lang == "id") {
    define("_WELCOME", "Selamat Datang");
    define("_HOME", "Beranda");
    define("_SEARCH", "Cari");
    define("_DASHBOARD", "Dashboard");
    define("_FAVOURITE", "Favorit");
    define("_PROFILE", "Profil");
    define("_USERPROFILE", "Profil Pengguna");
    define("_USERGUIDE", "Buku Petunjuk");
    define("_HELP", "Bantuan");
    define("_LANGUAGE", "Bahasa");
    define("_LOGOUT", "Keluar");
    define("_5LATESTSOP", "5 SOP Terbaru");
    define("_5LATESTIM", "5 Internal Memo Terbaru");
    define("_TITLE", "Judul");
    define("_DATE", "Tanggal");
    define("_DOCUMENT", "Dokumen");
    define("_PAGE", "Halaman");
    define("_SEARCHRESULT", "Hasil pencarian dari");
    define("_SELECT", "Pilih");
    define("_CATEGORY", "Kategori");
    define("_ALL", "Semua");
    define("_ACTIVITYREPORT", "Laporan Aktifitas Pengguna");
    define("_5LASTREAD", "5 Dokumen Terakhir Dibaca");
    define("_5MOSTREAD", "5 Dokumen Paling Sering Dibaca");
    define("_CODE", "Kode");
    define("_ADDTOFAVOURITE", "Tambah ke favorit");
    define("_DELETEFROMFAVOURITE", "Hapus dari favorit");
    define("_VIEWDOCUMENT", "Lihat detil dokumen");
    define("_DATE_SOP", "Tanggal SK");
    define("_DATE_IM", "Tanggal Memo");
    define("_DATE_READING", "Tanggal Baca");
    define("_BACK", "Kembali");
    define("_POPULARBOOK", "Buku Populer");
    define("_NEWBOOK", "Buku Terbaru");
    define("_AUTHOR", "Pengarang");
    define("_PUBLISHER", "Penerbit");
    define("_LOCATION", "Lokasi");
    define("_READ", "Baca");
    define("_FILENAME", "Nama File");
    define("_SIZE", "Ukuran");
    define("_YEAR", "Tahun");
    define("_DESC", "Deskripsi");
    define("_BOOKDETAIL", "Detail Buku");
    define("_RATING", "Rating");
    define("_BOOK", "Buku");
    define("_SHOW", "Menampilkan");
    define("_ORDER", "Urutkan");
    define("_NEW", "Terbaru");
    define("_OLD", "Terlama");
    define("_HIGHEST", "Rating Tertinggi");
    define("_TYPE", "Jenis");
    define("_PHYSICAL", "Buku Fisik");
    define("_DIGITAL", "Buku Digital");
    define("_ABOVE", "Ke Atas");
    define("_BORROW", "Dipinjam");
    define("_BY", "Oleh");
    define("_PREVIOUS", "Sebelum");
    define("_NEXT", "Sesudah");
    define("_INFORMATION", "Informasi, Berita, Artikel");
    define("_MORE", "Lihat Selengkapnya");
    define("_REC", "Rekomendasi Buku");
    define("_AVAILABLE", "Ketersediaan");
    define("_ALREADYREAD", "Sudah Membaca Buku ini?");
    define("_SHARE", "Bagikan Pendapat anda dengan pembaca lainnya");
    define("_DESCRIPTION", "Deskripsi");
    define("_SEND", "Kirim");
    define("_BOOKMARKADD", " Tambah ke Bookmark");
    define("_BOOKMARKDELETE", " Hapus dari Bookmark");
    define("_THOUGHT", "Bagikan Pendapat mu");
    define("_NEWS", "Berita");
    define("_INFORMATION2", "Informasi");
    define("_ARTICLE", "Artikel");
    define("_DETAIL", "Detail");
    define("_RACK", "Rack");
    





    // define("_AUTHOR", "Kembali");
}
